/* Challenge - Joining on multiple tables. Write SQL queries to perform the following tasks 
using the Sakila database:*/

/* 1.List the number of films per category */
SELECT name, COUNT(film_id)
FROM category
INNER JOIN film_category
ON sakila.film_category.Category_id = sakila.category.Category_id
GROUP BY name;

/* 2.Retrieve the store ID, city, and country for each store */
SELECT store_id, city, country
FROM country
INNER JOIN (
			SELECT store_id, city, country_id
			FROM city
			INNER JOIN (
						SELECT address.address_id, address.address, address.city_id, store.store_id
						FROM store
						INNER JOIN address
						ON address.address_id = store.address_id) AS store
			ON store.city_id = city.city_id) AS city
ON country.country_id = city.country_id;

/* 3. Calculate the total revenue generated by each store in dollars */
SELECT  store_id, CONCAT("$", SUM(amount)) AS total_revenue
FROM sakila.store
INNER JOIN sakila.payment
ON sakila.store.manager_staff_id = sakila.payment.staff_id
GROUP BY store_id;

/* 4. Determine the average running time of films for each category.*/
SELECT film_category.category_id, ROUND(AVG(film.length)) AS running_time
FROM sakila.film_category
INNER JOIN sakila.film
ON film.film_id = film_category.film_id
GROUP BY film_category.category_id;

### some exercises have sakila.database as prefix others don't, because at a certain point i just used as default.
### :)   <3   !